baseURL = 'https://nel.re/'
languageCode = 'en-us'
title = 'Nel.re'
theme = ["hugo-video", "nel-theme" ]

[module]
  [[module.imports]]
    path = "github.com/mfg92/hugo-shortcode-gallery"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menus.main]]
    identifier = "Art"
    name = 'Art'
    pageRef = '/art'
    weight = 20

  [[menus.main]]
    identifier = "Blog"
    name = 'Blog'
    pageRef = '/blog'
    weight = 30

  [[menus.main]]
    identifier = "Projects"
    name = 'Projects'
    pageRef = '/projects'
    weight = 40
